/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnreadCountResponse } from '../../models/unread-count-response';

export interface UnreadByType$Params {
}

export function unreadByType(http: HttpClient, rootUrl: string, params?: UnreadByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnreadCountResponse>>> {
  const rb = new RequestBuilder(rootUrl, unreadByType.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UnreadCountResponse>>;
    })
  );
}

unreadByType.PATH = '/notifications/unread-by-type';
