/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignmentAdminView } from '../../models/assignment-admin-view';

export interface GetAssignmentsByShipmentId$Params {
  'shipment-id': string;
}

export function getAssignmentsByShipmentId(http: HttpClient, rootUrl: string, params: GetAssignmentsByShipmentId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AssignmentAdminView>>> {
  const rb = new RequestBuilder(rootUrl, getAssignmentsByShipmentId.PATH, 'get');
  if (params) {
    rb.path('shipment-id', params['shipment-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AssignmentAdminView>>;
    })
  );
}

getAssignmentsByShipmentId.PATH = '/assignments/{shipment-id}';
