/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsignorProfileView } from '../../models/consignor-profile-view';

export interface GetConsignorByPhone$Params {
  phone: string;
}

export function getConsignorByPhone(http: HttpClient, rootUrl: string, params: GetConsignorByPhone$Params, context?: HttpContext): Observable<StrictHttpResponse<ConsignorProfileView>> {
  const rb = new RequestBuilder(rootUrl, getConsignorByPhone.PATH, 'get');
  if (params) {
    rb.path('phone', params.phone, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConsignorProfileView>;
    })
  );
}

getConsignorByPhone.PATH = '/consignors/{phone}';
