/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseConsignorProfileView } from '../../models/page-response-consignor-profile-view';

export interface GetPageOfConsignors$Params {
  page?: number;
  size?: number;
}

export function getPageOfConsignors(http: HttpClient, rootUrl: string, params?: GetPageOfConsignors$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseConsignorProfileView>> {
  const rb = new RequestBuilder(rootUrl, getPageOfConsignors.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseConsignorProfileView>;
    })
  );
}

getPageOfConsignors.PATH = '/consignors/all';
