/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TrackingResponse } from '../../models/tracking-response';

export interface GetLatest$Params {
  'assignment-id': string;
}

export function getLatest(http: HttpClient, rootUrl: string, params: GetLatest$Params, context?: HttpContext): Observable<StrictHttpResponse<TrackingResponse>> {
  const rb = new RequestBuilder(rootUrl, getLatest.PATH, 'get');
  if (params) {
    rb.path('assignment-id', params['assignment-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TrackingResponse>;
    })
  );
}

getLatest.PATH = '/tracking/{assignment-id}/latest';
