/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseRegisteredUsers } from '../../models/page-response-registered-users';

export interface GetPageOfRegisteredUsers$Params {
  page?: number;
  size?: number;
}

export function getPageOfRegisteredUsers(http: HttpClient, rootUrl: string, params?: GetPageOfRegisteredUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseRegisteredUsers>> {
  const rb = new RequestBuilder(rootUrl, getPageOfRegisteredUsers.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseRegisteredUsers>;
    })
  );
}

getPageOfRegisteredUsers.PATH = '/identity/registered-users';
