/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserProfile } from '../../models/user-profile';

export interface UpdateUserProfile$Params {
      body: UserProfile
}

export function updateUserProfile(http: HttpClient, rootUrl: string, params: UpdateUserProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfile>> {
  const rb = new RequestBuilder(rootUrl, updateUserProfile.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProfile>;
    })
  );
}

updateUserProfile.PATH = '/identity';
