/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleProfileView } from '../../models/vehicle-profile-view';

export interface GetVehicleByDriver$Params {
  'driver-id': string;
}

export function getVehicleByDriver(http: HttpClient, rootUrl: string, params: GetVehicleByDriver$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VehicleProfileView>>> {
  const rb = new RequestBuilder(rootUrl, getVehicleByDriver.PATH, 'get');
  if (params) {
    rb.path('driver-id', params['driver-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VehicleProfileView>>;
    })
  );
}

getVehicleByDriver.PATH = '/vehicles/profile/{driver-id}';
