/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseShipmentSummary } from '../../models/page-response-shipment-summary';

export interface GetPageOfShipmentsByStage$Params {
  stage: 'NEW' | 'AGREED' | 'EXECUTION' | 'COMPLETED' | 'CANCELLED';
  page?: number;
  size?: number;
}

export function getPageOfShipmentsByStage(http: HttpClient, rootUrl: string, params: GetPageOfShipmentsByStage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseShipmentSummary>> {
  const rb = new RequestBuilder(rootUrl, getPageOfShipmentsByStage.PATH, 'get');
  if (params) {
    rb.path('stage', params.stage, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseShipmentSummary>;
    })
  );
}

getPageOfShipmentsByStage.PATH = '/shipments/stage/{stage}';
