/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentResponse } from '../../models/shipment-response';

export interface GetConsignorShipments$Params {
}

export function getConsignorShipments(http: HttpClient, rootUrl: string, params?: GetConsignorShipments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getConsignorShipments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipmentResponse>>;
    })
  );
}

getConsignorShipments.PATH = '/shipments/consignor';
