/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentOfferDto } from '../../models/shipment-offer-dto';

export interface GetShipmentOffers$Params {
  'shipment-id': string;
}

export function getShipmentOffers(http: HttpClient, rootUrl: string, params: GetShipmentOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentOfferDto>>> {
  const rb = new RequestBuilder(rootUrl, getShipmentOffers.PATH, 'get');
  if (params) {
    rb.path('shipment-id', params['shipment-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipmentOfferDto>>;
    })
  );
}

getShipmentOffers.PATH = '/shipment-offers/{shipment-id}';
