/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminRequestChange {
  deliveryDate?: string;
  loadingDate?: string;
  priceAmount?: number;
  reason?: string;
  requiredVehicleNumber?: number;
  requiredVehicleType?: string;
  shipmentId?: string;
}
