/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminInitialDriverOfferRequest {
  driverIds?: Array<string>;
  offeredPrice?: number;
  remark?: string;
  shipmentId?: string;
}
