/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignmentAdminView {
  agreedPrice?: number;
  assignedAt?: string;
  assignedBy?: string;
  cancelReason?: string;
  cancelledAt?: string;
  completedAt?: string;
  consignorConfirmedAt?: string;
  driverCompletedAt?: string;
  driverId?: string;
  driverStartedAt?: string;
  publicId?: string;
  remark?: string;
  shipmentId?: string;
  startLatitude?: number;
  startLocation?: string;
  startLongitude?: number;
  startedAt?: string;
  status?: 'DRIVER_ASSIGNED' | 'GDN_GENERATED' | 'LOADING_CONFIRMED' | 'IN_TRANSIT' | 'DELIVERED' | 'OFFLOADING_CONFIRMED' | 'GRN_GENERATED' | 'CONSIGNOR_CONFIRMED' | 'CANCELLED' | 'REOPENED_BY_ADMIN';
}
