/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignmentDriverView {
  agreedPrice?: number;
  assignedAt?: string;
  cancelReason?: string;
  cancelledAt?: string;
  completedAt?: string;
  consignorConfirmedAt?: string;
  driverCompletedAt?: string;
  driverStartedAt?: string;
  publicId?: string;
  shipmentId?: string;
  startedAt?: string;
  status?: string;
}
