/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConsignorCounterReq {
  counterPrice?: number;
  deliveryDate?: string;
  loadingDate?: string;
  reason?: string;
  requiredVehicleNumber?: number;
  requiredVehicleType?: string;
  shipmentId?: string;
}
