/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGdnRequest {
  consigneeContact?: string;
  consigneeName?: string;
  packagingType?: string;
  quantity?: number;
  remarks?: string;
  volume?: string;
  weight?: string;
}
