/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDriverProfileRequest {
  licenceDocument?: string;
  licenceNumber?: string;
  nationalId?: string;
  preferredLanes?: string;
  profilePic?: string;
}
