/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateShipmentRequest {
  deliveryDate?: string;
  details?: string;
  goodType?: string;
  loadingDate?: string;
  loadingLocation?: string;
  offloadingLocation?: string;
  price?: number;
  priceType?: string;
  quantity?: number;
  requiredVehicleNumber?: number;
  requiredVehicleType?: string;
  route?: string;
  volume?: string;
  weight?: string;
}
