/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateVehicleRequest {
  details?: string;
  insuranceDoc?: string;
  photo?: string;
  plateNumber?: string;
  type?: string;
}
