/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverOfferView {
  details?: string;
  goodType?: string;
  loadingLocation?: string;
  negotiationId?: string;
  offloadingLocation?: string;
  priceAmount?: number;
  priceCurrency?: string;
  priceType?: string;
  requiredVehicleNumber?: number;
  requiredVehicleType?: string;
  status?: string;
  volume?: string;
  weight?: string;
}
