/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverNegotiationResponse {
  createdAt?: string;
  driverId?: string;
  finalAgreedPrice?: number;
  publicId?: string;
  shipmentId?: string;
  startLatitude?: number;
  startLocation?: string;
  startLongitude?: number;
  status?: 'CREATED' | 'OFFER_SENT' | 'DRIVER_COUNTERED' | 'ADMIN_COUNTERED' | 'DRIVER_ACCEPTS' | 'DRIVER_REJECTS' | 'EXPIRED' | 'SELECTED' | 'NOT_SELECTED' | 'DRIVER_CANCEL' | 'CANCELED';
  updatedAt?: string;
}
