/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserProfile } from '../models/user-profile';
export interface PageResponseUserProfile {
  content?: Array<UserProfile>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
