/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  confirmPassword?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  phoneNumber?: string;
  role?: 'SUPER_ADMIN' | 'ADMIN' | 'DRIVER' | 'CONSIGNOR';
}
