/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShipmentStatusHistoryDto {
  changedAt?: string;
  changedBy?: string;
  reason?: string;
  status?: string;
}
