/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShipmentOfferDto {
  deliveryDate?: string;
  loadingDate?: string;
  offeredAt?: string;
  offeredBy?: string;
  priceAmount?: number;
  reason?: string;
  requiredVehicleNumber?: number;
  requiredVehicleType?: string;
  round?: number;
}
