/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TrackingRecordRequest {
  accuracy?: number;
  assignmentId?: string;
  latitude?: number;
  longitude?: number;
  recordedAt?: string;
  speed?: number;
}
