/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleProfileView {
  details?: string;
  insuranceDoc?: string;
  phone?: string;
  photo?: string;
  plateNumber?: string;
  publicId?: string;
  status?: string;
  type?: string;
}
