/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentStatusHistoryDto } from '../../models/shipment-status-history-dto';

export interface GetShipmentStatusHistory$Params {
  'shipment-id': string;
}

export function getShipmentStatusHistory(http: HttpClient, rootUrl: string, params: GetShipmentStatusHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentStatusHistoryDto>>> {
  const rb = new RequestBuilder(rootUrl, getShipmentStatusHistory.PATH, 'get');
  if (params) {
    rb.path('shipment-id', params['shipment-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipmentStatusHistoryDto>>;
    })
  );
}

getShipmentStatusHistory.PATH = '/shipment-status-history/{shipment-id}';
